export const GET_CONTACT_REQUEST = "GET_CONTACT_REQUEST"
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS"
export const GET_CONTACT_FAILURE = "GET_CONTACT_FAILURE"

export const POST_CONTACT_REQUEST = "POST_CONTACT_REQUEST"
export const POST_CONTACT_SUCCESS = "POST_CONTACT_SUCCESS"
export const POST_CONTACT_FAILURE = "POST_CONTACT_FAILURE"

export const EDIT_CONTACT_REQUEST = "EDIT_CONTACT_REQUEST"
export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACT_SUCCESS"
export const EDIT_CONTACT_FAILURE = "EDIT_CONTACT_FAILURE"

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST"
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS"
export const DELETE_CONTACT_FAILURE = "DELETE_CONTACT_FAILURE"